### ISSUE TITLE
No physics on smp items.

### ISSUE THREAD

**Issue by ArbiterMC** [DaymareOn/hdtSMP64#125]
The bug happens when I try to use an item that has SMP capabilities.

Not fully sure how to reproduce the bug. I dont have HDT-SMP. I use LOOT, but nothing changed.

**Expected behavior**
Expected to have physics on SMP items.

**Screenshots and videos**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11, Nvidia RTX 3060, Intel i7

** FSMP**
- Says "not yet"
- NOT CUDA
- No AVX

**SKSE**
- 2.2.6
(You can check it in the bottom left part of the screen, when looking at your MCMs.)

**Skyrim**
- 1.6.1170
(You can check it in the bottom left part of the screen, when looking at your MCMs.)

**Required files**
N/A

**Additional context**
Just confused on how to get this to work.

**Comment by RemixRemm** [comment]
i'm having the same issue trying to get physics to work too, i've been looking all over but i believe its mostly due to the fact that FSMP isn't up to date with the current version of skyrim. there is talk of a test version on the "new versions information and tests" forum, however, virustotal is flagging it for potential phishing so i have just decided to wait until the newest update is officially released. here is the link to the forum: https://www.nexusmods.com/skyrimspecialedition/mods/57339/?tab=forum&topic_id=10699058

**Comment by snottyone** [comment]
at the moment, THERE IS NO FSMP VERSION FOR 1170
whatever is floating in the forum is done by some amateur and DOES NOT WORK

**Comment by DaymareOn** [comment]
Well, not an amateur, he's igloomod, a fine fellow, credited in FSMP :)
