### ISSUE TITLE
[BUG] one little bug at the beginning of the game

### ISSUE THREAD

**Issue by mikejames3151** [DaymareOn/hdtSMP64#130]
**Describe the bug**

When I installed FSMP, I found that at the beginning of the game, the reins on the carriage were floating in the air and not well connected to the horse.
**To Reproduce**

**Expected behavior**

**Screenshots and videos**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Wine]

** FSMP**
lasted version

**SKSE**
- installed version
lasted version

**Skyrim**
- Installed version number
lasted version

**Required files**
- Join your configs.xml
- Join your hdtSMP64.log

**Additional context**

**Comment by mikejames3151** [comment]
thank you.but [this fix](https://www.nexusmods.com/skyrimspecialedition/mods/60968) havent solve my problem.i found this problem only when i use fsmp,everything will be ok when i turn off fsmp.Although it's a small problem, it has indeed troubled me for a long time

**Comment by snottyone** [comment]
it has troubled everyone since the game was released :)
so, it's not fsmp, but some armor mod you are using which is physics enabled, and those cause the problem. you can also cause the glitch with schlongs of sykrim (yes, really).
the only way to do the carriage ride without problems is to disable all mods, and re-enable them once out of the cave. and it's so totally not worth it.
it's why everyone is using Alternate Start - Live Another Life.

**Comment by DaymareOn** [comment]
Strange, I'd like to know how FSMP / physics-enabled mods impact this.
