### ISSUE TITLE
The AVX512 versions don't work for 1.6.640

### ISSUE THREAD

**Issue by beelixx** [DaymareOn/hdtSMP64#79]
**Describe the bug**
cant comment on nexus
15 discussion threads that are a mess
cant bug report on nexus
have to make github account to even bring this up

use fomod for 1.6.640 on any release in the last 2months
non cuda avx512 never works
some other options sometimes do

**To Reproduce**
1. download mod
2. iinstall mod
3. click 1.6.40 options
4. game refuses to launch bc its a dll made for a game version before 1.6.40
5. hate your life because it wont work and you cant tell anyone

**Expected behavior**
game to launch

**Screenshots and videos**
black screen game says incompatable hdtblahblah.dll

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Wine]

** FSMP**
- Installed version
- CUDA: both - i only care about non-cuda though
- AVX: all - only care about avx512 though

**Required files**
- use literal same as in mod
- wont launch no log

**Additional context**
like just check the version files for EVERY file in the fomod im assuming its just repackaging the right dlls pointing to the right things but could be wrong. dont know if its a sensitivity thing based on the massive bit on the mod page about removing and banning everyone but making it so that users have to go thru hell and high water to bug report is a little wack although i respect its ur mod u do u

**Comment by beelixx** [comment]
cuda/avx2 - launches
cuda/avx512 - doesnt launch
no cuda/no avx - launches
no cuda/avx2 - launches
no cuda/avx 512 - doesnt launch

youd have to check the rest thats all i have time to test like i said just seems some were j missed or simple repackage

**Comment by DaymareOn** [comment]
beelixx, about the bug report process, I answered you on Nexus.

"dont know if its a sensitivity thing based on the massive bit on the mod page about removing and banning everyone"
You mean when I banned one user from my mods because he implied I was a liar and a thief? That was at the beginning of FSMP, more than one year ago, no link whatsoever.
I moved the bug reports here, because at least I can use templates to remind people of what they should provide in the bug report. 3 bug reports out of 4 were unusable on the Nexus, and a time loss.

About this bug, you said you haven't time to test; well I haven't any AVX-512 CPU, so I can't test.
To be honest, this bug won't be looked at any further until I have some meaningful information.

"black screen game says incompatable hdtblahblah.dll"
Would you please give the complete message error? It's the only useful information in your bug report, excepted "AVX512 doesn't work on 1.6.640".
And, if it's related to SKSE (I imagine it is), could you please give your skse version number? You have it on the left bottom part of the screen when opening your MCMs.

**Comment by snottyone** [comment]
better late than never:
you wouldn't by chance have an intel 12xxx cpu?

> Intel does not officially support AVX-512 family of instructions on the Alder Lake microprocessors. Intel has disabled in silicon (fused off) AVX-512 on recent steppings of Alder Lake microprocessors to prevent customers from enabling AVX-512.  In older Alder Lake family CPUs with some legacy combinations of BIOS and microcode revisions, it was possible to execute AVX-512 family instructions when disabling all the efficiency cores which do not contain the silicon for AVX-512.

**Comment by DaymareOn** [comment]
Intel information added to the fomod.
